### ISSUE TITLE
Using findMany without any default 'where' condition

### ISSUE THREAD

**Issue by biancouver** [olivierwilkinson/prisma-soft-delete-middleware#1]
Hi @olivierwilkinson, 

Thank you for putting this useful library together! I have quick question for you: in my project, I'm using `.findMany` without any query (I just want Prisma to return all rows from my tables). For example:

```
await prisma.user.findMany()
```

But when doing so, it seems that the library is expecting a `where` fetch condition, that does not exist in this use case: 

`Cannot read properties of undefined (reading 'where')`

I might be wrong but `params` in [createFindManyParams](https://github.com/olivierwilkinson/prisma-soft-delete-middleware/blob/main/src/lib/actionMiddleware.ts#L220-L237) is maybe `undefined`.

As a workaround, adding an initial `where` condition resolves the issue. For example

```
await prisma.user.findMany({
  where: {
    deletedAt: null
  },
}))
```

Or even an empty query, since the middleware will add the `deletedAt` automatically:

```
await prisma.user.findMany({
  where: {},
}))
```

But that defeats the purpose of having the middleware do it for you. 

I was wondering if maybe there should be an extra `const where = args.where || {};` in `createFindManyParams`. Unless there is a particular reason to always have to provide a `where` filter?

Here is my client configuration, if it helps:

```
client.$use(
  createSoftDeleteMiddleware({
    models: {
      User: true,
    },
    defaultConfig: {
      field: 'deletedAt',
      createValue: deleted => (deleted ? new Date() : null),
    },
  })
)
```

Thank you for your time and help.

**Comment by olivierwilkinson** [comment]
Heya 👋 

Thanks for raising this, I'm glad you are finding it useful! I should be able to get on this later today 😄

**Comment by biancouver** [comment]
Thanks for the quick response 🙌🏻

**Comment by olivierwilkinson** [comment]
Hey again,

I didn't mention in my previous comment but this was definitely a bug and not intentional, I missed that findMany does not need args or a where object! I fixed that issue, and looked into other queries to avoid the same problem happening elsewhere.

I've just merged the fix, so it should be available as v1.0.1 in the next 10 mins or so. Let me know if it works in your project, I'll reopen if not!

Thanks again for raising this 🙌

**Comment by biancouver** [comment]
Awesome! I'll definitely give it a try and I'll keep you posted in here 👍🏻

**Comment by biancouver** [comment]
@olivierwilkinson I cannot reproduce the issue with that new 1.0.1 release 🎉  Thanks again for the quick fix 🙌🏻

**Comment by olivierwilkinson** [comment]
No worries at all! 😁
