### ISSUE TITLE
Middlewares are deprecated

### ISSUE THREAD

**Issue by TArch64** [olivierwilkinson/prisma-soft-delete-middleware#12]
Hi! Since prisma v4.16 middlewares were deprecated. Do you have any plans to migrate to extensions? I found [this extension](https://prisma-extensions.io/#soft-delete) but it doesn't work with v5

```ts
// From @prisma/client/index.ts

/**
 * Add a middleware
 * @deprecated since 4.16.0. For new code, prefer client extensions instead.
 * @see https://pris.ly/d/extensions
*/
$use(cb: Prisma.Middleware): void
```

**Comment by olivierwilkinson** [comment]
Hi there, yeah I do plan to migrate to extensions! There is a related issue in the prisma-nested-middleware repo [about moving to extensions](https://github.com/olivierwilkinson/prisma-nested-middleware/issues/26). I've pretty much got that working, I just need to fix the types, and then I'll move onto moving this middleware into a new extension. 👍

**Comment by darr1s** [comment]
I'm looking to create an auditable plugin repo as well currently referencing a lot from your repo. Thanks and keep up with the great work.

**Comment by olivierwilkinson** [comment]
I have finished porting this library to an extension! It can be found at [prisma-extension-soft-delete](https://github.com/olivierwilkinson/prisma-extension-soft-delete), it is also published on npm under the same name.

Let me know if you find any issues or have any questions! (and please give it a star if you feel like it 😄)
