### ISSUE TITLE
support findFirstOrThrow

### ISSUE THREAD

**Issue by tomhoffen** [olivierwilkinson/prisma-soft-delete-middleware#14]
Hi,

Im using findFirstOrThrow many in my app and I wonder what is the effort to support it as well.
From my understanding its just adding this action to **middlewareByModel** function in:
https://github.com/olivierwilkinson/prisma-soft-delete-middleware/blob/main/src/lib/createSoftDeleteMiddleware.ts#L68

Thank you

**Comment by olivierwilkinson** [comment]
Hi there,

just wanted to let you know that I'm looking into this, I also thought it would be as simple as adding the findFirst middleware handler under the findFirstOrThrow field of middlewareByModel but it's failing some tests I added.

I'll have some time to work on it this weekend, if not sooner 👍

**Comment by tomhoffen** [comment]
Thanks man, I appreciate it!

**Comment by olivierwilkinson** [comment]
All fixed, this should be available in v1.2.0! 😄 

Thanks again for raising this and please let me know if you have any other problems 👍
