### ISSUE TITLE
$use: @deprecated — since 4.16.0. For new code, prefer client extensions instead.  @see — https://pris.ly/d/extensions

### ISSUE THREAD

**Issue by pq43** [olivierwilkinson/prisma-soft-delete-middleware#18]
<img width="787" alt="image" src="https://github.com/olivierwilkinson/prisma-soft-delete-middleware/assets/51523958/6a15ffdc-3c97-4351-aa80-a561a474b598">

Just worth noting. Not a big issue, thank you so much for this open source repo :)

**Comment by olivierwilkinson** [comment]
Thanks for raising this, I have actually ported this library to an extension already! It can be found at https://github.com/olivierwilkinson/prisma-extension-soft-delete

I'll definitely add a note about this in the description as it's not obvious until quite far down in the readme!

**Comment by pq43** [comment]
ahh, that's awesome thank you! sorry for that :)
