### ISSUE TITLE
findUnique({ where: { id: undefined } }) should throw an exception

### ISSUE THREAD

**Issue by pond918** [olivierwilkinson/prisma-soft-delete-middleware#4]
currently, it executes sql:  ... WHERE "entity"."deleted" = $1 LIMIT 1 OFFSET 0
which returns an unwanted entity.

**Comment by olivierwilkinson** [comment]
Hi there 👋

Thanks for raising this!

Just wanted to let you know that I'm looking into this, it's a little more tricky than expected but I think I'll have a fix sometime this week / early next week.
